/**
 * Data models for the LLM Wiki Second Brain system.
 * 
 * These interfaces define the core data structures used throughout the wiki system:
 * - WikiPage: AI-generated wiki pages with frontmatter and cross-references
 * - RawSource: Immutable source documents stored in raw/ directory
 * - ActivityLogEntry: Chronological record of wiki operations
 * - MaintenanceReport: Findings from periodic wiki maintenance
 */

/**
 * Represents a section within a wiki page.
 * Sections are hierarchical and can contain subsections.
 */
export interface Section {
  /** The heading text of the section */
  heading: string;
  
  /** The heading level (1-6 for h1-h6) */
  level: number;
  
  /** The markdown content of the section */
  content: string;
  
  /** Nested subsections within this section */
  subsections: Section[];
}

/**
 * Represents an AI-generated wiki page.
 * Wiki pages are stored in the wiki/ directory and contain structured content
 * with frontmatter metadata and cross-references to related pages.
 */
export interface WikiPage {
  /** Relative path from wiki/ directory */
  path: string;
  
  /** File name */
  filename: string;
  
  /** YAML frontmatter metadata */
  frontmatter: {
    /** Page title */
    title: string;
    
    /** Page type: entity (specific thing), concept (idea/pattern), or source (summary) */
    type: 'entity' | 'concept' | 'source';
    
    /** Tags for categorization and search */
    tags: string[];
    
    /** References to raw source files (optional) */
    sources?: string[];
    
    /** Author name (for source summaries) */
    author?: string;
    
    /** Publication date (for source summaries) */
    date?: string;
    
    /** Source URL (for source summaries) */
    url?: string;
    
    /** ISO date when page was created */
    created: string;
    
    /** ISO date when page was last updated */
    updated: string;
  };
  
  /** Markdown body content */
  content: string;
  
  /** Parsed sections from the markdown content */
  sections: Section[];
  
  /** [[WikiLink]] references in this page (outgoing links) */
  outgoingLinks: string[];
  
  /** Pages that link to this page (incoming links/backlinks) */
  incomingLinks: string[];
}

/**
 * Represents an immutable source document stored in raw/ directory.
 * Raw sources are never modified after ingestion and serve as the
 * foundation for AI-generated wiki pages.
 */
export interface RawSource {
  /** Relative path from raw/ directory */
  path: string;
  
  /** Original filename */
  filename: string;
  
  /** File format/type */
  format: 'md' | 'pdf' | 'txt' | 'code';
  
  /** Subdirectory category (e.g., 'articles', 'papers', 'code-snippets') */
  category: string;
  
  /** Date when file was added to repository */
  addedDate: Date;
  
  /** File size in bytes */
  fileSize: number;
  
  /** File content (string for text files, Buffer for binary files) */
  content: string | Buffer;
  
  /** Whether this source has been processed into wiki pages */
  ingested: boolean;
  
  /** Paths to wiki pages generated from this source */
  generatedPages: string[];
}

/**
 * Represents an entry in the activity log.
 * Activity log entries track all wiki operations chronologically.
 */
export interface ActivityLogEntry {
  /** Timestamp of the operation */
  timestamp: Date;
  
  /** Type of operation performed */
  type: 'creation' | 'update' | 'ingestion';
  
  /** Path to the wiki page (for creation and update operations) */
  pagePath?: string;
  
  /** Title of the wiki page (for creation and update operations) */
  pageTitle?: string;
  
  /** Type of the wiki page (for creation and update operations) */
  pageType?: 'entity' | 'concept' | 'source';
  
  /** Description of changes made (for update operations) */
  changes?: string;
  
  /** Reason for the update (for update operations) */
  reason?: string;
  
  /** Path to the raw source file (for ingestion operations) */
  sourcePath?: string;
  
  /** Wiki pages generated from ingestion (for ingestion operations) */
  generatedPages?: string[];
  
  /** Tags associated with the operation */
  tags?: string[];
}

/**
 * Represents a maintenance report generated by periodic wiki review.
 * Maintenance reports identify issues and opportunities for improvement.
 */
export interface MaintenanceReport {
  /** Timestamp when the report was generated */
  timestamp: Date;
  
  /** Duplicate or overlapping content detected */
  duplicates: {
    /** First page with duplicate content */
    page1: string;
    
    /** Second page with duplicate content */
    page2: string;
    
    /** Similarity score (0-1) */
    similarity: number;
    
    /** Recommendation for resolving the duplicate */
    recommendation: string;
  }[];
  
  /** Contradictory information detected across pages */
  contradictions: {
    /** Pages containing contradictory information */
    pages: string[];
    
    /** Description of the contradiction */
    contradiction: string;
    
    /** Severity level of the contradiction */
    severity: 'low' | 'medium' | 'high';
  }[];
  
  /** Broken [[WikiLink]] references detected */
  brokenLinks: {
    /** Page containing broken links */
    page: string;
    
    /** List of broken link targets */
    brokenLinks: string[];
  }[];
  
  /** Opportunities to consolidate related pages */
  consolidationOpportunities: {
    /** Pages that could be consolidated */
    pages: string[];
    
    /** Reason for consolidation suggestion */
    reason: string;
    
    /** Suggested action to take */
    suggestedAction: string;
  }[];
  
  /** Orphaned pages with no incoming links */
  orphans: {
    /** Path to orphaned page */
    page: string;
    
    /** Reason why this page is orphaned */
    reason: string;
  }[];
  
  /** Summary statistics about wiki health */
  summary: {
    /** Total number of wiki pages */
    totalPages: number;
    
    /** Total number of cross-reference links */
    totalLinks: number;
    
    /** Overall health score (0-100) */
    healthScore: number;
  };
  
  /** ADR-specific maintenance findings (optional) */
  adrFindings?: {
    /** Broken session references in ADR pages */
    brokenSessionReferences: {
      /** Page with broken session reference */
      page: string;
      
      /** Session ID that cannot be found */
      sessionId: string;
      
      /** Validation errors */
      errors: string[];
      
      /** Suggested corrective actions */
      suggestedActions: string[];
    }[];
    
    /** Duplicate library entity pages */
    duplicateLibraries: {
      /** Library name */
      libraryName: string;
      
      /** Entity pages for this library */
      entityPages: string[];
      
      /** ADRs that reference this library */
      referencedByADRs: string[];
      
      /** Suggested consolidation action */
      suggestedAction: string;
    }[];
    
    /** Superseded research decisions */
    supersededDecisions: {
      /** Page with superseded decision */
      page: string;
      
      /** Decision title */
      title: string;
      
      /** Decision status */
      status: string;
      
      /** Page that supersedes this decision (if known) */
      supersededBy?: string;
      
      /** Recommendation for handling */
      recommendation: string;
    }[];
    
    /** Broken cross-references in ADR pages */
    adrCrossReferenceIssues: {
      /** Page with broken cross-references */
      page: string;
      
      /** Broken link targets */
      brokenLinks: string[];
      
      /** Suggested corrective actions */
      suggestedActions: string[];
    }[];
  };
}
