import type * as d3 from 'd3';

/** The three categories a wiki page can belong to. */
export type NodeType = 'entity' | 'concept' | 'source';

/**
 * A single wiki page represented as a node in the graph.
 * Requirement 1.2: one node per page, title from frontmatter as identifier.
 * Requirement 1.3: type and tags extracted from frontmatter.
 * Requirement 1.5: isGhost marks nodes for broken wikilink targets.
 */
export interface GraphNode {
  /** Normalized (lowercase) title — used as the stable key in GraphData.nodes. */
  id: string;
  /** Display title from YAML frontmatter. */
  title: string;
  /** Page category derived from frontmatter `type` field. */
  type: NodeType;
  /** Tags array from frontmatter; empty array when absent. */
  tags: string[];
  /** Relative path within wiki/, e.g. "entities/angular-cdk.md". Empty for ghost nodes. */
  filePath: string;
  /** True when the page does not exist in the wiki (broken wikilink target). */
  isGhost: boolean;
  /** Number of edges pointing INTO this node. Computed after the full graph is built. */
  inDegree: number;
  /** Number of edges pointing OUT of this node. Computed after the full graph is built. */
  outDegree: number;
}

/**
 * A directed connection from one wiki page to another.
 * Requirement 1.4: one edge per unique [[wikilink]] in the source page body.
 */
export interface GraphEdge {
  /** id of the source GraphNode. */
  sourceId: string;
  /** id of the target GraphNode (may be a ghost node). */
  targetId: string;
}

/**
 * The complete in-memory graph produced by WikiParserService.
 * Requirement 1.8: contains all nodes and edges derived from the wiki directory.
 */
export interface GraphData {
  /** All nodes keyed by node.id (normalized title). */
  nodes: Map<string, GraphNode>;
  /** All directed edges in the graph. */
  edges: GraphEdge[];
  /** Deduplicated, sorted list of all tags present across all non-ghost nodes. */
  allTags: string[];
}

/**
 * Extends GraphNode with mutable position fields required by the D3 force simulation.
 * D3ForceRenderer uses this type internally; Angular components never reference it.
 */
export interface SimulationNode extends GraphNode, d3.SimulationNodeDatum {
  x?: number;
  y?: number;
  fx?: number | null;
  fy?: number | null;
}

/**
 * Shape of wiki/manifest.json — generated by `nx run wiki-cli:generate-manifest`.
 * WikiParserService fetches this first to discover all .md file paths.
 * Requirement 1.1: lists all .md files in entities/, concepts/, and sources/.
 */
export interface WikiManifest {
  /** Relative paths from wiki/, e.g. ["entities/angular-cdk.md", "concepts/signals.md"]. */
  files: string[];
  /** ISO timestamp of when the manifest was generated. */
  generatedAt: string;
}
